
import React, {Component} from "react";
import PushNotification from "react-native-push-notification";
import firebase from './firebase'


export default class NotifService extends Component {

  
  state = {
    lastId:0
  }

  componentDidMount(){
    PushNotification.configure({
        // (optional) Called when Token is generated (iOS and Android)
        
        onRegister: (token) => {
          var user = firebase.auth().currentUser;

          firebase.database().ref(`users/${user.uid}/token`).once('value').then(function (snapshot) {
            if (snapshot == undefined){
              firebase.database().ref(`users/${user.uid}`).set({
                token : token.token
              })
            } else if (snapshot.val() != token.token){
              firebase.database().ref(`users/${user.uid}`).update({
                token : token.token
              })
            }
          })
          console.log("TOKEN:", token);
        },
        
        // (required) Called when a remote or local notification is opened or received
        onNotification: async (notification) => {
          console.log("NOTIFICATION:", notification);
          this.localNotif(notification);
          // process the notification here
      
        },
        // Android only
        senderID: "543229345691",
        // iOS only
        permissions: {
          alert: true,
          badge: true,
          sound: true
        },
        popInitialNotification: true,
        requestPermissions: true
      });
  }

    localNotif(notification) {
        PushNotification.localNotification({
          /* Android Only Properties */
          id: '' + this.state.lastId++, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
          ticker: 'My Notification Ticker', // (optional)
          autoCancel: true, // (optional) default: true
          largeIcon: null, // (optional) default: "ic_launcher"
          smallIcon: 'ic_notification', // (optional) default: "ic_notification" with fallback for "ic_launcher"
          
          color: 'grey', // (optional) default: system default
          vibrate: true, // (optional) default: true
          vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
          tag: 'some_tag', // (optional) add tag to message
          group: 'group', // (optional) add group to message
          ongoing: false, // (optional) set whether this is an "ongoing" notification
  
        
          /* iOS and Android properties */
          title: "You have a new friend request!", // (optional)
          message: "Check it out on your profile", // (required)
          playSound: false, // (optional) default: true
          soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
          number: 10, // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
        // (Android only) See the doc for notification actions to know more
        });
      
      
    }

    render(){
        return null;
    }
  
}